INSERT INTO CAR (BRAND, MODEL, PLATE) VALUES('MARCA 1', 'MODELO 1', 'MATRICULA 1');
INSERT INTO CAR (BRAND, MODEL, PLATE) VALUES('MARCA 2', 'MODELO 2', 'MATRICULA 2');
INSERT INTO CAR (BRAND, MODEL, PLATE) VALUES('MARCA 3', 'MODELO 3', 'MATRICULA 3');
INSERT INTO CAR (BRAND, MODEL, PLATE) VALUES('MARCA 4', 'MODELO 4', 'MATRICULA 4');
INSERT INTO CAR (BRAND, MODEL, PLATE) VALUES('MARCA 5', 'MODELO 5', 'MATRICULA 5');
INSERT INTO CAR (BRAND, MODEL, PLATE) VALUES('MARCA 6', 'MODELO 6', 'MATRICULA 6');
INSERT INTO CAR (BRAND, MODEL, PLATE) VALUES('MARCA 7', 'MODELO 7', 'MATRICULA 7');
INSERT INTO CAR (BRAND, MODEL, PLATE) VALUES('MARCA 8', 'MODELO 8', 'MATRICULA 8');
