INSERT INTO VEHICLE (PLATE) VALUES('MATRICULA 1');
INSERT INTO VEHICLE (PLATE) VALUES('MATRICULA 2');
INSERT INTO VEHICLE (PLATE) VALUES('MATRICULA 3');
INSERT INTO VEHICLE (PLATE) VALUES('MATRICULA 4');
INSERT INTO VEHICLE (PLATE) VALUES('MATRICULA 5');
INSERT INTO VEHICLE (PLATE) VALUES('MATRICULA 6');
INSERT INTO VEHICLE (PLATE) VALUES('MATRICULA 7');
INSERT INTO VEHICLE (PLATE) VALUES('MATRICULA 8');
